POST /products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWNmZWRjMmYxMTczNWZiMWY4NDdlNWQiLCJpYXQiOjE3MDgxMzQ5MTQsImV4cCI6MTcwODEzNTgxNH0.ekytSrP9z3vF_rMJO13Q_NVxCLsmCblV_-IZKTbOMLM
