(function(g){var window=this;'use strict';var W3=function(a){a.oa("cardstatechange",a.Mk()&&a.gp()?1:0)},X3=function(a,b){var c=g.bb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Zlb=function(a){var b=g.os(a);
a=g.rs(a);return new g.ds(b.x,b.y,a.width,a.height)},$lb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.JC(a,b,function(){g.KC(e);c.apply(a,arguments)},d)},$3=function(a){a=g.gb(a);
delete Y3[a];g.ld(Y3)&&Z3&&Z3.stop()},bmb=function(){Z3||(Z3=new g.Ru(function(){amb()},20));
var a=Z3;a.isActive()||a.start()},amb=function(){var a=g.lb();
g.ad(Y3,function(b){cmb(b,a)});
g.ld(Y3)||bmb()},a4=function(a,b,c,d){g.dv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},cmb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;dmb(a,a.progress);1==a.progress?(a.j=0,$3(a),a.onFinish(),a.lr()):a.isPlaying()&&a.AL()},dmb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},emb=function(a,b){g.Bb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},b4=function(a,b,c,d,e){a4.call(this,b,c,d,e);
this.element=a},fmb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
b4.call(this,a,b,c,d,e)},gmb=function(a){return Math.pow(a,3)},hmb=function(a){return 3*a*a-2*a*a*a},imb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},c4=function(a){return a.baseUrl||null},d4=function(a,b){return g.pt(g.Ar(a,b),function(c){return!!c})},jmb=function(a,b,c){function d(ua){var ma=ua.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var sa=f(ma.unsubscribedButtonText),da=f(ma.subscribedButtonText);if(ma.subscribed){var ba=f(ma.subscriberCountWithUnsubscribeText);var Ma=f(ma.subscriberCountText)}else ba=f(ma.subscriberCountText),Ma=f(ma.subscriberCountWithSubscribeText);var y=null;if(ua.signinEndpoint){y=X3(ua,"signinEndpoint","webNavigationEndpointData","url");if(!y){var Y,Ta;y=null==(Ta=g.U(null==(Y=ma.signInEndpoint)?void 0:Y.commandMetadata,g.R2))?void 0:
Ta.url}if(!y)return null}return sa&&(da||y)?{subscribed:ma.subscribed,subscribeText:sa,subscribeCount:ba,unsubscribeText:da,unsubscribeCount:Ma,enabled:ma.enabled,signinUrl:y,classic:ua.useClassicSubscribeButton}:null}
function e(ua){if(ua){var ma=[],sa=ua.videoId;sa&&ma.push("v="+sa);(sa=ua.playlistId)&&ma.push("list="+sa);(ua=ua.startTimeSeconds)&&ma.push("t="+ua);return"/watch?"+ma.join("&")}}
function f(ua){if(!ua)return null;var ma=ua.simpleText;return ma?ma:ua.runs?g.Ar(ua.runs,function(sa){return sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,B=null,E=null,F=null,G=null,N=null,M=null;if("VIDEO"===h)g.U(l,g.zG)?m=g.U(l,g.zG).url:(M=g.U(l,g.rT),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.U(l,g.zG)?m=g.U(l,g.zG).url:(M=g.U(l,g.rT),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=X3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((F=X3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=X3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=X3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
ha="";if(b.metadata){var va=f(b.metadata);va&&(ha=va)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ha,callToAction:f(b.callToAction),dW:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,ZD:p,playlistLength:t,channelId:v,subscribeButton:B,subscribersText:E,isSubscribe:x,targetUrl:m||null,l8:n,sessionData:R?{itct:R}:null,Hca:q,BC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:d4(b.impressionUrls||[],c4),Y7:d4(b.hovercardShowUrls||[],c4),clickUrls:d4(l.loggingUrls||[],c4),visualElement:g.yF(b.trackingParams),productPrice:G,additionalFeesText:N,watchEndpoint:M||null}},kmb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:d4(a.impressionUrls||[],c4),elements:d4(a.elements||[],function(d,e){return jmb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.yF(a.trackingParams));return c},lmb=function(a){g.bW.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.jS(a)||g.lS(a);this.events=new g.UK(this);g.O(this,this.events);this.events.T(this.player,g.gK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.hK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Yb);this.events.T(window,"focus",this.Taa);this.load();var b=g.rf("STYLE");(g.Ve("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.wf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},mmb=function(a){return a.player.getVideoData().Of?"current":a.Z?"new":"current"},e4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},nmb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=kmb(f,mmb(a))));f4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Ox;d&&(c.postParams={ad_tracking:d});if(b=g.nTa(b))if(b=g.Wn(b),b=g.he(b))a.C=g.aC(b,c)},f4=function(a,b,c){c=void 0===c?!0:c;
a.player.Df("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&omb(a);c=[];d=new g.fK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.V({I:"div",S:"ytp-ce-shadow"}),g.yU(a.player,a.B.element,4),a.D=new g.MG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=pmb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.yU(a.player,f.element,4);var h=new g.fK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);qmb(a,f,e)}else g.EF(new g.$C("buildEndscreenElement null",
e))}a.player.xf(c);a.Yb()}},omb=function(a){var b=g.zF(),c=g.AF();
c&&b&&a.endscreen.visualElement&&g.JB(g.NF)(void 0,c,b,a.endscreen.visualElement)},pmb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",La:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.BC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:g4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:h4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.ov(b.title||"")},ya:b.title},{I:"div",S:b.ZD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={I:"div",La:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.BC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:g4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:h4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.ov(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={I:"div",La:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.BC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",La:["ytp-ce-channel-title","ytp-ce-link"],X:{href:h4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.ov(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",La:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:g4(b)}]};c=new g.V(c);var d=g.We(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Zu(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.JW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",La:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.BC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.ov(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",La:["ytp-ce-website-goto","ytp-ce-link"],X:{href:h4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:g4(b)},{I:"div",S:"ytp-ce-expanding-icon",X:rmb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",La:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.BC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.ov(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",La:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:h4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:g4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.Zu(c.element,"ytp-ce-placeholder");return c},g4=function(a){if(a.dW)var b=a.dW.thumbnails;
return rmb(b?b[b.length-1].url:null)},rmb=function(a){return a?{style:"background-image: url("+a+")"}:{}},qmb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Zu(b.element,"ytp-ce-force-expand"),i4(a,c.id,!0)):(g.av(b.element,"ytp-ce-force-expand"),g.av(b.element,"ytp-ce-element-hover"),i4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){smb(a,b,c)});
b.Ta("mouseleave",function(){tmb(a,b,c)});
a.player.U().B||b.Ta("click",function(){g.Zu(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){umb(a,c,m)});
b.Ta("keypress",function(m){umb(a,c,m)});
b.Ta("focus",function(){smb(a,b,c)});
b.Ta("blur",function(){tmb(a,b,c)});
b.Ta("touchstart",function(){smb(a,b,c)});
var l=g.$e("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.av(b.element,"ytp-ce-element-hover");g.av(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.$e("ytp-sb-subscribe",b.element));d(g.$e("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},umb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Yu(d,"ytp-ce-element");){g.Yu(d,"subscribe-label")&&vmb(a,b);
if(g.Yu(d,"ytp-ce-channel-subscribe"))return;d=g.xf(d)}if(!d||g.Yu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])tmb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Hca)vmb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Wn(h4(a,b.targetUrl)),g.nH(g.he(c),void 0,b.sessionData);else{var e=g.uS(a.player.U())||a.player.getVideoData().Of,f=function(){var h=h4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.OB(h);e&&n&&(n.v||
n.list)?a.player.Lo(n.v,l,n.list,!1,void 0,m||void 0):g.wxa(h,l)};
vmb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},h4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.BS(a)+b}else return"";return b},smb=function(a,b,c){g.Yu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Zu(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Ru(function(){g.Zu(b.element,"ytp-ce-element-hover")},200)).start():g.Zu(b.element,"ytp-ce-element-hover"),j4(a,c.Y7),i4(a,c.id,!0))},tmb=function(a,b,c){g.av(b.element,"ytp-ce-element-hover");
g.av(b.element,"ytp-ce-force-expand");i4(a,c.id,!1)},i4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.cv(a.j[e].element,"ytp-ce-element-shadow-show",c)},j4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||e4(a))c&&c();else{b=wmb(a,b);var e=0,f=!1,h=new g.Ru(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.tE(b[a],d)}},vmb=function(a,b,c){j4(a,b.clickUrls,c);
(a=g.AF())&&b.l8&&g.UF(a,b.visualElement)},wmb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(xmb(b[d],c));return a},xmb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},ymb=function(a){return"string"===typeof a?a:""},k4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},zmb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},l4=function(a){return a.value?a.value:null},m4=function(a){if(!a)return null;
var b=g.Wn(ymb(a.value));b=g.he(b);if(!b)return null;var c=k4(a.target,Amb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new zmb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Bmb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Emb=function(a){if(!a)return null;
var b=k4(a.type,Cmb),c=k4(a.trigger,Dmb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=m4(a?a:null);return b?new Bmb(b,c,a):null},Fmb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Gmb=function(a,b){return g.Eb(a.action,b)},Hmb=function(a,b){this.context=a;
this.j=b},Imb=function(a){return a.customMessage?n4("div","iv-card-message",a.customMessage):""},o4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Jmb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(n4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},n4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.ov(c);return{I:a,X:b,ya:c}},Kmb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.LC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.LC+");");c.dir=g.ov(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",La:b,X:c,V:d}},p4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.nj.click,5)}},Lmb=function(a,b){this.merchant=a;
this.price=b},Mmb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Nmb=function(a,b){return b?b:Mmb(a)?"current":"new"},q4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Xa=new Map;this.gb=new Map;this.context.J.addEventListener(g.gK("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.hK("annotations_module"),function(d){(d=c.gb.get(d))&&d.apply(c)})},r4=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.BL(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.rb=!1});
a.context.j.Ta(b,"touchmove",function(){a.rb=!0})},Omb=function(a){var b;
return(null==(b=g.U(a,g.zG))?0:b.url)?g.U(a,g.zG).url:(a=g.U(a,g.rT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},s4=function(a,b,c){return{FX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
e0:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
QK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Pmb=function(a,b,c){q4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.Na=this.Lb=this.C=this.isInitialized=!1;this.cards=[];this.ub=this.Z=this.Ma=this.G=this.Wa=this.j=null;this.ma=[];this.ra=this.N=this.Mf=this.Ga=null;this.K=0;this.Ia=new g.Ru(function(){},c.W.Kl?4E3:3E3);
g.O(this,this.Ia);this.kb=new g.Ru(function(){});
g.O(this,this.kb);this.Ca=new Hmb(c,function(e,f,h,l,m,n){r4(d,e,f,h,l,m,n)});
this.Y=new g.V({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",La:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.O(this,this.Y);this.D=this.Y.element;this.Za=new g.MG(this.Y,330);g.O(this,this.Za);this.Pb=g.$e("iv-drawer-header-text",this.D);this.B=g.$e("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Lb&&t4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Lb=d.C)&&u4(d)});
this.Ra=new g.UK(this);g.O(this,this.Ra);this.J.addEventListener("videodatachange",this.kt.bind(this))},Qmb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){t4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){u4(a)});
var c=b.headerText;g.zf(a.Pb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.yF(b.trackingParams);a.N=g.yF(b.closeTrackingParams);a.Mf=g.yF(b.iconTrackingParams)},Rmb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.nG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,nj:{},ip:null,Oj:e.trackingParams?g.yF(e.trackingParams):null,Mf:f&&f.trackingParams?g.yF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
LC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};v4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.nG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:w4(a,c,b,f),sponsored:!1,nj:s4(f,e,f.command),ip:f.trackingParams?g.yF(f.trackingParams):null,Oj:e.trackingParams?g.yF(e.trackingParams):null,Mf:l&&l.trackingParams?g.yF(l.trackingParams):null,imageUrl:x4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.nG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,LC:null,title:f.title?g.nG(f.title):"",customMessage:f.callToAction?g.nG(f.callToAction):"",url:g.U(f.command,g.zG).url?m4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.zG).url}):null,onClickCommand:null};v4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.nG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:w4(a,c,b,e),sponsored:!1,nj:s4(e,f,e.endpoint),ip:e.trackingParams?g.yF(e.trackingParams):null,Oj:f.trackingParams?g.yF(f.trackingParams):null,Mf:l&&l.trackingParams?g.yF(l.trackingParams):null,channelId:g.U(e.endpoint,g.GT).browseId,customMessage:e.customText?g.nG(e.customText):null,profileImageUrl:x4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.nG(e.channelName):"",metaInfo:[e.subscriberCountText?g.nG(e.subscriberCountText):""],url:m4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(e.endpoint,g.GT).canonicalBaseUrl?g.U(e.endpoint,g.GT).canonicalBaseUrl:"/channel/"+g.U(e.endpoint,g.GT).browseId}),onClickCommand:null};v4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.nG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:w4(a,c,b,e),sponsored:!1,nj:s4(e,f,e.action),ip:e.trackingParams?g.yF(e.trackingParams):null,Oj:f.trackingParams?g.yF(f.trackingParams):null,Mf:l&&l.trackingParams?g.yF(l.trackingParams):null,dG:x4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.nG(e.customMessage):null,playlistVideoCount:g.nG(e.playlistVideoCount),title:e.playlistTitle?g.nG(e.playlistTitle):"",metaInfo:[e.channelName?g.nG(e.channelName):
"",e.videoCountText?g.nG(e.videoCountText):""],url:m4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Omb(e.action)}),onClickCommand:null};v4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.nG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:w4(a,c,b,e),sponsored:!1,nj:s4(e,f,e.action),ip:e.trackingParams?g.yF(e.trackingParams):null,Oj:f.trackingParams?g.yF(f.trackingParams):null,Mf:l&&l.trackingParams?g.yF(l.trackingParams):null,dG:x4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.nG(e.lengthString):null,customMessage:e.customMessage?g.nG(e.customMessage):null,title:e.videoTitle?g.nG(e.videoTitle):"",metaInfo:[e.channelName?g.nG(e.channelName):
"",e.viewCountText?g.nG(e.viewCountText):""],isLiveNow:!!e.badge,url:m4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Omb(e.action)}),onClickCommand:null};v4(a,b)}}}}}a.K++},x4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},w4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Tmb=function(a,b){if(b=Smb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.If.id),g.wf(b.SM),g.Jb(a.cards,b),a.bH(),y4(a)},t4=function(a,b,c){if(!a.C){a.Za.show();
a.Wa=new g.Ru(function(){g.Zu(a.context.J.getRootNode(),g.vZ.IV_DRAWER_OPEN)},0);
a.Wa.start();a.Ra.T(a.B,"mousewheel",function(h){a.Ia.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.AF();d&&a.Ga&&a.N&&g.SF(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.vY||(f.vY=!0,Umb(a.context.logger,f.If.nj.FX,b)),d&&g.SF(d,[f.If.ip]);W3(a.J);c&&(a.G=new g.Ru(function(){a.Ma=a.Z;a.ub.focus()},330),a.G.start())}},u4=function(a){a.C&&(a.Za.hide(),g.PC(a.Ra),g.av(a.context.J.getRootNode(),g.vZ.IV_DRAWER_OPEN),a.C=!1,W3(a.J),a.G&&a.G.stop(),a.G=new g.Ru(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.G.start())},Wmb=function(a){g.$u(a.Kb(),
[g.vZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.yU(a.J,a.D,5);Vmb(a);a.Z=g.$e("ytp-cards-button",a.J.getRootNode());a.ub=g.$e("iv-drawer-close-button",a.D);a.isInitialized=!0},Vmb=function(a){var b=g.$e("iv-drawer-close-button",a.D);
a.context.j.Ta(b,"click",a.I5,a);a.context.j.Ta(a.B,"touchend",function(){a.Ia.start()});
a.context.j.Ta(a.B,"scroll",a.f6,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Yu(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.HE("iv-button-shown",a.D8,a));a.ma.push(g.HE("iv-button-hidden",a.C8,a));Xmb(a)},Xmb=function(a){a.ma.push(g.HE("iv-teaser-shown",a.X1,a));
a.ma.push(g.HE("iv-teaser-hidden",a.E8,a));a.ma.push(g.HE("iv-teaser-clicked",a.W1,a));a.Ab=!0},Ymb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.U(b.onClickCommand,g.wib))?void 0:c.targetId)?(a.ra=b,!0):!1},Zmb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.LRa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.U(h[0],g.s0a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},v4=function(a,b){if(!Ymb(a,b)||Zmb(a,b)){var c=$mb(a,b);
if(c){var d={If:b,SM:c.element,vY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||Xmb(a),Tmb(a,b.id),c=a.findLastIndex(d),g.Sb(a.cards,c,0,d));else{a.isInitialized||Wmb(a);Tmb(a,b.id);var e=a.findLastIndex(d);g.Sb(a.cards,e,0,d);c.Ja(a.B,e);a.bH()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,y4(a),anb(a,d),t4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&bnb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){bnb(a,d)}),y4(a))}}},$mb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=Kmb(b);c={I:"div",La:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?l4(b.url)||"":""},V:[o4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[n4("h2",void 0,b.title),d]}]}]};c=new g.V(c);p4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",La:["iv-card","iv-card-channel"],V:[{I:"a",La:["iv-click-target"],X:{href:l4(b.url)||"","data-ytid":b.channelId},V:[o4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Imb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},Jmb(b)]}]}]};c=new g.V(c);p4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",La:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:l4(b.url)||""},V:[o4(b.dG,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Imb(b),n4("h2","iv-card-primary-link",b.title),Jmb(b)]}]}]};
c=new g.V(c);p4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Kmb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?l4(b.url)||"":"";c={I:"div",La:c,X:{tabindex:"0"},V:[{I:"a",La:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[n4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.rf("span");g.zf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Ud(d,"adInfo");p4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",La:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={I:"div",La:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:l4(c))||""},V:[o4(b.dG,d),{I:"div",S:"iv-card-content",V:[Imb(b),n4("h2","iv-card-primary-link",b.title),Jmb(b),f]}]}]};c=new g.V(e);p4(a,g.Ze("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},cnb=function(a){if(a.j)return"productListing"===a.j.If.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Br(a.cards,function(c){return"productListing"===c.If.type})}return g.Br(a.cards,function(c){return"productListing"===c.If.type})},y4=function(a){g.cv(a.J.getRootNode(),"ytp-cards-shopping-active",cnb(a))},bnb=function(a,b){if(!g.Yu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.AF(),d=a.j?a.j.If.Mf:a.Mf;
c&&d&&g.TF(c,[d]);a.j=b;y4(a)}(c=a.isInitialized&&"none"==a.Kb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.If.teaserDurationMs&&a.J.iB(!0,{teaserText:b.If.teaserText,durationMs:b.If.teaserDurationMs,onClickCommand:b.If.onClickCommand});a.kb.isActive()||((!a.C||!a.Ia.isActive()&&a.Na)&&anb(a,b),a.kb.start(910+b.If.teaserDurationMs))}},anb=function(a,b){a.Y.Hb?(b=new a4([0,
a.B.scrollTop],[0,b.SM.offsetTop],600,hmb),a.context.C.Ta(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ta(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.dG(a.Y,!0),a.B.scrollTop=b.SM.offsetTop,g.dG(a.Y,!1))},z4=function(a){return a.j&&a.j.If?a.j.If:a.cards[0]&&a.cards[0].If?a.cards[0].If:null},Smb=function(a,b){return g.Eb(a.cards,function(c){return c.If.id===b})},A4=function(a,b,c){q4.call(this,a,b);
this.annotation=c;this.isActive=!1},dnb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},B4=function(a,b,c){A4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},enb=function(a,b){var c=void 0===c?0:c;
var d=Zlb(b).width;g.ms(b,d);c=new fmb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,gmb);g.O(a,c);a.context.C.Ta(c,"begin",function(){g.ts(b,!0)});
c.play()},hnb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
La:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",La:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.JW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",La:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",La:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.ts(h,!1);var l=a.createElement({I:"div",La:["branding-context-container-outer"]});l.appendChild(h);g.gs(l,"right",b.image_width+"px");g.tf(a.Kb(),l);a.C=new g.Ru(function(){fnb(a,h,l)},500);
g.O(a,a.C);a.context.j.Ta(a.Kb(),"mouseover",function(){gnb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Kb(),"mouseout",function(){a.C.start()})}},gnb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.rs(b);a.j||(b.style.width=g.ls(f.width,!0),c.style.width=g.ls(f.width,!0));g.gs(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.gs(d,"right","1px");a.D=!0;g.ts(b,!0);a.G=new g.Ru(function(){g.Zu(this.Kb(),"iv-branding-active")},0,a);
a.G.start()}},fnb=function(a,b,c){g.av(a.Kb(),"iv-branding-active");
a.K=new g.Ru(function(){g.ts(b,!1);a.j||(c.style.width=g.ls(0,!0))},250);
a.K.start();a.D=!1},inb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},jnb=function(a,b,c){A4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",La:["iv-promo-contents"]});this.G=new g.Ru(function(){d.j.setAttribute("aria-hidden","true");g.ts(d.C,!1);g.ts(d.B,!0)},700,this);
g.O(this,this.G)},mnb=function(a,b,c){c.stopPropagation();
knb(a);lnb(a,b);a.j.focus()},nnb=function(a){a.isCollapsed||a.Z||a.D||(g.Zu(a.Kb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},knb=function(a){a.G.stop();
a.isCollapsed&&(g.bv(a.Kb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.ts(a.B,!1),g.ts(a.C,!0))},lnb=function(a,b){a.D||(a.D=g.lg(function(){onb(this);
nnb(this)},b,a))},onb=function(a){a.D&&(g.Sa.clearTimeout(a.D),a.D=null)},pnb=function(a){this.J=a},Umb=function(a,b,c){b&&(c?C4(a,b.map(function(d){return g.Gu(d,c)})):C4(a,b))},C4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.tE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},qnb=function(a){g.bW.call(this,a);
var b=this;this.ma=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new pnb(this.player);this.D=new g.UK(this);this.G=this.K=null;this.events=new g.UK(this);this.Zg=this.Y=this.j=null;this.ra=[];g.O(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.Y1,this);this.subscribe("resize",this.EJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.yZ,this);g.O(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.V({I:"div",La:["ytp-player-content","ytp-iv-player-content"]});g.O(this,this.B);g.yU(this.player,this.B.element,4);this.B.hide();this.C=new g.V({I:"div",La:["ytp-iv-video-content"]});g.O(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.mu()&&this.load();var c=this.createElement({I:"style"});(g.Ve("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.wf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},rnb=function(a){a=a.createElement({I:"div",
La:["annotation","annotation-type-custom"]});g.ts(a,!1);return a},snb=function(a,b){b=!b.isCued()&&!g.TG(b,1024);
g.dG(a.B,b);g.dG(a.C,b)},tnb=function(a,b,c){a.Z=!0;
a.G=g.aC(b,c)},unb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.cb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(unb(a,e))}return c},ynb=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.WB(h)&&h.responseXML?h.responseXML:null)&&vnb(a,h)}};
g.hD()&&(d.onFinish=wnb(a,d.onFinish));d.postParams={ic_only:"1"};xnb(d,c);a.Z=!0;g.aC(b.Wa,d)}}},xnb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.gH&&(a.postParams.ic_coll=b.gH);b.TM&&(a.postParams.ic_xml=b.TM);b.VK&&(a.postParams.ic_track=b.VK)},znb=function(a){var b=new g.V({I:"div"});
g.ts(b.element,!1);var c=new Pmb(a.player,b.element,D4(a));g.O(c,b);b.Ja(a.B.element);c.OF();return c},Bnb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ma=!0,Anb(a,b),b.headerText&&a.Zg&&(c=g.nG(b.headerText),a.Zg.setAttribute("title",c))},D4=function(a){if(!a.Y){var b=new imb(a);
g.O(a,b);var c=new g.vp(a);g.O(a,c);a.Y=new inb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Cj)}return a.Y},vnb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.AF();if(e){var f=g.zF();f&&g.JB(g.Wva)(void 0,e,f,[g.yF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=unb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=k4(f.type,Cnb),p=k4(f.style,Dnb),q=ymb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Emb;if(null==t)var v=null;else if(g.bb(t)){l=[];for(var x=g.u(t),B=x.next();!B.done;B=x.next()){var E=f(B.value);
E&&l.push(E)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Fmb(m,n,p,v,r):null}else e=null}catch(va){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=rnb(f),N=null;switch(l.type){case "branding":if(f.player.U().Fe)break;f.B.element.appendChild(G);N=new B4(G,D4(f),l);break;case "promotion":g.yU(f.player,G,4),N=new jnb(G,D4(f),l)}N&&N.OF();if(f=N)g.O(a,f),a.N[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=znb(a),g.O(a,a.j));if("card"===e.type){G=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={FX:f.impression,click:f.click,close:f.close,e0:f.teaser_impression,QK:f.teaser_click},l=e.tracking_params||{},N=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,ip:l.card?g.yF(l.card):null,Oj:l.teaser?g.yF(l.teaser):null,Mf:l.icon?g.yF(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};v4(G,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,
ip:l.card?g.yF(l.card):null,Oj:l.teaser?g.yF(l.teaser):null,Mf:l.icon?g.yF(l.icon):null,dG:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};v4(G,c);break;case "productListing":e.signin_url&&(N=m4({target:"current",value:e.signin_url}));M=[];for(var R=e.offers||[],ha=0;ha<R.length;ha++)M.push(new Lmb(g.Je(R[ha].merchant),
g.Je(R[ha].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,ip:l.card?g.yF(l.card):null,Oj:l.teaser?g.yF(l.teaser):null,Mf:l.icon?g.yF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,LC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),kob:N,job:e.signin_title?e.signin_title:void 0,iob:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};v4(G,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,ip:l.card?g.yF(l.card):
null,Oj:l.teaser?g.yF(l.teaser):null,Mf:l.icon?g.yF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,LC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};v4(G,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,ip:l.card?g.yF(l.card):null,Oj:l.teaser?g.yF(l.teaser):null,Mf:l.icon?g.yF(l.icon):null,dG:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},v4(G,c)}}else Qmb(a.j,e);c=!0}}c&&
(W3(a.player),a.EJ())},Anb=function(a,b){var c=!1;
a.j||(a.j=znb(a),g.O(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Rmb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.NT(f)||(c=a.j,d=b.headerText?g.nG(b.headerText):"",g.zf(c.Pb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.yF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.yF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Mf=b.icon.infoCardIconRenderer.trackingParams?g.yF(b.icon.infoCardIconRenderer.trackingParams):null,a.EJ());W3(a.player)}},Enb=function(a,b,c,d,e){if(!a.player.U().Fe){var f=[];
b.navigationEndpoint&&g.U(b.navigationEndpoint,g.GT)&&g.U(b.navigationEndpoint,g.GT).browseId&&f.push(new Bmb("openUrl","click",new zmb("/channel/"+g.U(b.navigationEndpoint,g.GT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.U(b.subscribeButton,
g.HT)){d.channel_id=g.U(b.subscribeButton,g.HT).channelId;var l;b=g.U(b.subscribeButton,g.HT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.nG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.nG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.nG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.nG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.U(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.R2))?void 0:m.url)||"";l={subscribeText:g.nG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.nG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Fmb(c,"branding","branding",f,d);l=rnb(a);a.B.element.appendChild(l);f=new B4(l,D4(a),f);f.OF();g.O(f,f);a.N[c]=f}},wnb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.ra.push(g.Ju.Yi(function(){b.apply(null,g.oa(c))}))}},Fnb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.rU.prototype.iB=g.ea(29,function(a,b){var c=g.rW(this.Cb());c&&c.iB(a,b)});
var Y3={},Z3=null;g.pb(a4,g.dv);g.k=a4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;$3(this);this.startTime=a=g.lb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.wJ();this.fm("play");this.isPaused()&&this.fm("resume");this.j=1;var b=g.gb(this);b in Y3||(Y3[b]=this);bmb();cmb(this,a);return!0};
g.k.stop=function(a){$3(this);this.j=0;a&&(this.progress=1);dmb(this,this.progress);this.fm("stop");this.lr()};
g.k.pause=function(){this.isPlaying()&&($3(this),this.j=-1,this.fm("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.fm("destroy");a4.Tf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.AL=function(){this.fm("animate")};
g.k.fm=function(a){this.dispatchEvent(new emb(a,this))};
g.pb(emb,g.Bb);g.pb(b4,a4);b4.prototype.C=function(){};
b4.prototype.AL=function(){this.C();b4.Tf.AL.call(this)};
b4.prototype.lr=function(){this.C();b4.Tf.lr.call(this)};
b4.prototype.wJ=function(){this.C();b4.Tf.wJ.call(this)};
g.pb(fmb,b4);fmb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(imb,g.I);g.k=imb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.JC(a,b,c);this.j.push(a);return a};
g.k.VI=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=$lb(a,b,c);this.j.push(a);return a};
g.k.Tc=function(a){g.KC(a);g.Jb(this.j,a)};
g.k.Cf=function(){g.KC(this.j);this.j.length=0};
g.k.xa=function(){this.Cf();g.I.prototype.xa.call(this)};g.w(lmb,g.bW);g.k=lmb.prototype;g.k.load=function(){g.bW.prototype.load.call(this);if(!e4(this)){var a=g.oTa(this.player.getVideoData());a?(a=kmb(a,mmb(this)),f4(this,a,!1)):nmb(this)}};
g.k.unload=function(){f4(this,null);this.C&&(this.C.abort(),this.C=null);g.bW.prototype.unload.call(this)};
g.k.Lh=function(a,b){return e4(this)?"loadCustomEndscreenRenderer"===a?(a=kmb(b,"new"),f4(this,a),!0):null:null};
g.k.getOptions=function(){return e4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Gnb.length;f++){var h=Math.abs(b.width-Gnb[f]);if(-1===e||d>=h)e=f,d=h}d=Hnb[e];this.B&&g.gs(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.qs(e.element,m,f);g.ms(e.element,n,p);g.bv(e.element,Inb);256<m||256<f?g.Zu(e.element,"ytp-ce-large-round"):96<m||96<f?g.Zu(e.element,"ytp-ce-medium-round"):g.Zu(e.element,"ytp-ce-small-round");g.bv(e.element,Jnb);m=h.left+h.width/2;h=h.top+l/2;g.Zu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.bv(e.element,Hnb);g.Zu(e.element,d);(e=g.We(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.gs(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())j4(this,this.endscreen.impressionUrls),(a=g.AF())&&this.endscreen.visualElement&&g.RF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Zu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Zu(b,"ytp-ce-shown");j4(this,c.impressionUrls);(b=g.AF())&&g.RF(b,c.visualElement);this.player.U().K&&this.player.ob("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.av(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.av(b,"ytp-ce-shown");this.player.U().K&&this.player.ob("endscreenelementhidden",a)}};
g.k.Taa=function(a){var b=this;a.target===window&&(new g.Ru(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.bv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Gnb=[346,426,470,506,570,640,853,1280,1920],Hnb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Jnb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Inb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Amb={nua:"current",aVa:"new"};var Cmb={CLOSE:"close",QYa:"openUrl",SUBSCRIBE:"subscribe"},Dmb={vsa:"click",CLOSE:"close",hGa:"hidden",S3a:"rollOut",T3a:"rollOver",F5a:"shown"};Fmb.prototype.Ue=function(){var a=Gmb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Dnb={Xma:"anchored",t1:"branding",CHANNEL:"channel",Zta:"cta",kGa:"highlightText",lKa:"label",PLAYLIST:"playlist",y0a:"popup",F8a:"speech",SUBSCRIBE:"subscribe",ubb:"title",VIDEO:"video",Vib:"website"},Cnb={t1:"branding",cqa:"card",owa:"drawer",jGa:"highlight",xQa:"marker",f2a:"promotion",TEXT:"text",Akb:"widget"};g.w(q4,g.I);g.k=q4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.fK(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.gb.set(a,e);this.context.J.xf([a])};
g.k.OF=function(){this.context.B.subscribe("resize",this.bH,this)};
g.k.Kb=function(){return this.element};
g.k.BL=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.wf(this.Kb())};
g.k.bH=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=l4(a);if(f){var h=Nmb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Of||!1,n=g.OB(f||"");m&&n&&(n.v||n.list)?e.context.J.Lo(n.v,b,n.list,!1):g.nH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);C4(this.context.logger,c,l,d);Mmb(f)||(c=g.AF(),d=b.itct,c&&d&&g.UF(c,g.yF(d)))}};
g.k.xa=function(){this.Xa.clear();this.gb.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.O(this,a);return a.element};g.w(Pmb,q4);g.k=Pmb.prototype;g.k.kt=function(){this.ra&&v4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.rs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.bH=function(){var a=this.isAvailable();g.ts(this.Kb(),a);g.cv(this.context.J.getRootNode(),g.vZ.IV_DRAWER_ENABLED,a);W3(this.J)};
g.k.destroy=function(){this.J.iB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.IE(this.ma);g.PC(this.Ra);this.Wa&&this.Wa.dispose();this.G&&this.G.dispose();q4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Fb(this.cards,function(c){return a.If.startMs>c.If.startMs||a.If.startMs===c.If.startMs&&a.If.timestamp>=c.If.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.I5=function(){if(this.C){C4(this.context.logger,z4(this).nj.close);var a=g.AF();a&&this.N&&g.UF(a,this.N);u4(this)}};
g.k.f6=function(){g.cv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.D8=function(){var a=g.AF(),b=z4(this);b=b?b.Mf:this.Mf;a&&b&&g.SF(a,[b])};
g.k.C8=function(){var a=g.AF(),b=z4(this);b=b?b.Mf:this.Mf;a&&b&&g.TF(a,[b])};
g.k.X1=function(){var a=z4(this);C4(this.context.logger,a.nj.e0);var b=g.AF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Oj&&c.push(a.Oj);a.Mf&&c.push(a.Mf);0<c.length&&g.SF(b,c)}else g.SF(b,[a.Oj,a.Mf])};
g.k.E8=function(){var a=g.AF(),b=z4(this);a&&b&&g.TF(a,[b.Oj])};
g.k.W1=function(a){var b=z4(this),c=g.AF();this.j?a?(a=this.context.logger,C4(a,b.nj.QK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Oj&&g.UF(c,b.Oj)):(a=this.context.logger,C4(a,b.nj.QK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Mf&&g.UF(c,b.Mf)):(a=this.context.logger,C4(a,b.nj.QK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Mf&&g.UF(c,this.Mf))};g.w(A4,q4);A4.prototype.OF=function(){q4.prototype.OF.call(this);dnb(this)};
A4.prototype.show=function(){q4.prototype.show.call(this);var a=g.AF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.SF(a,[g.yF(b.itct)])};
A4.prototype.hide=function(){q4.prototype.hide.call(this);var a=g.AF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.TF(a,[g.yF(b.itct)])};g.w(B4,A4);B4.prototype.aB=function(){g.Zu(this.Kb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",La:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.ts(this.B,!1);var b=this.createElement({I:"button",La:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Kb().appendChild(b);var c=this.annotation.Ue();c&&r4(this,b,c,this.annotation.id,a.session_data);hnb(this,a)};
B4.prototype.show=function(){if(!this.isActive&&(A4.prototype.show.call(this),this.N||(this.aB(),this.N=!0),g.ts(this.Kb(),!0),this.isActive=!0,this.B)){try{enb(this,this.B)}catch(a){}g.Zu(this.context.J.getRootNode(),"ytp-branding-shown")}};
B4.prototype.hide=function(){this.isActive&&(A4.prototype.hide.call(this),g.ts(this.Kb(),!1),this.isActive=!1,g.av(this.context.J.getRootNode(),"ytp-branding-shown"))};
B4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);A4.prototype.destroy.call(this)};g.w(jnb,A4);g.k=jnb.prototype;
g.k.aB=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Kb().setAttribute("aria-hidden","true");this.Kb().setAttribute("aria-label","Promotion");this.Kb().tabIndex=0;var e=this.annotation.Ue(),f=b.image_url;if(f){var h=this.createElement({I:"div",La:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&r4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Zn(f,l4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",La:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",La:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&r4(this,
this.Kb(),e,this.annotation.id,b.session_data,void 0,c)}g.Zu(this.j,"iv-click-target");e&&r4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",La:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.Zu(this.j,"iv-click-target"),e&&r4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",La:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ta(this.B,"click",function(q){mnb(a,5E3,q)});
c.appendChild(this.B);g.ts(this.B,!1);this.context.j.Ta(this.Kb(),"mouseover",this.y7,this);this.context.j.Ta(this.Kb(),"mouseout",this.x7,this);this.context.j.Ta(this.Kb(),"touchend",function(q){mnb(a,5E3,q)});
this.C=this.createElement({I:"button",La:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ta(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.t7:this.s7,this);c.appendChild(this.C);g.$u(this.Kb(),d);h&&(g.tf(this.Kb(),h),n&&h.appendChild(n));g.tf(this.Kb(),this.N);g.tf(this.Kb(),c)};
g.k.show=function(){this.isActive||(A4.prototype.show.call(this),this.Y||(this.aB(),this.Y=!0),g.ts(this.Kb(),!0),g.lg(function(){g.av(this.Kb(),"iv-promo-inactive")},100,this),this.Kb().removeAttribute("aria-hidden"),this.isActive=!0,onb(this),knb(this),lnb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Zu(this.Kb(),"iv-promo-inactive"),this.isActive=!1,this.Kb().setAttribute("aria-hidden","true"))};
g.k.BL=function(a,b,c,d,e,f){return this.isCollapsed?!1:A4.prototype.BL.call(this,a,b,c,d,e,f)};
g.k.y7=function(a){this.Z=!0;mnb(this,500,a)};
g.k.x7=function(){this.Z=!1;nnb(this)};
g.k.s7=function(a){a.stopPropagation();this.hide()};
g.k.t7=function(a){a.stopPropagation();onb(this);this.isCollapsed=!0;g.Zu(this.Kb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();A4.prototype.destroy.call(this)};g.w(qnb,g.bW);g.k=qnb.prototype;g.k.Lh=function(a,b){if(!Fnb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.x2(b))&&vnb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Tmb(this.j,b),W3(this.player)),!0}return null};
g.k.getOptions=function(){return Fnb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.mu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.aU(b)||g.kU(this.player.app)?!1:1===c&&!b.TU||a.Na.get(b.videoId)||g.OT(b)||g.pTa(b)?!0:!1};
g.k.EJ=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.qs(this.C.element,a.width,a.height);g.ms(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Dn();a=this.j;b=b.width;g.cv(a.D,"iv-drawer-small",426>=b);g.cv(a.D,"iv-drawer-big",1280<=b)}};
g.k.Y1=function(a){snb(this,a.state);g.TG(a.state,2)&&(this.Mk()&&this.gp()&&2!==this.player.getPresentingPlayerType()&&this.jB(!1),this.iB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.WB(h)&&h.responseXML?h.responseXML:null)&&(vnb(b,h),g.Zu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.bW.prototype.load.call(this);snb(this,this.player.Ub());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.hD()&&(a=wnb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&xnb(e,f);f=f&&(f.TM||f.gH);if(!c.Hx||f)c.Wa?tnb(this,c.Wa,e):(this.K=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.NT(h))&&!b.ma&&Bnb(b,h)},this.player.addEventListener("videodatachange",this.K));
g.yU(this.player,this.C.element,4);this.EJ();(f=g.OT(c))&&Anb(this,f);(f=g.pTa(c))&&f.featuredChannel&&Enb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Zg=g.$e("ytp-cards-button",this.player.getRootNode());g.NT(c)&&Bnb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&tnb(this,b.Wa,a)};
g.k.unload=function(){this.player.Df("annotations_module");for(var a=g.u(Object.keys(this.N)),b=a.next();!b.done;b=a.next())this.N[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,W3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.ma=!1;this.N={};this.B.hide();g.bW.prototype.unload.call(this);this.C.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.k.yZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?ynb(this):this.load())};
g.k.Mk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ma};
g.k.gp=function(){return!!this.j&&this.j.C};
g.k.jB=function(a,b,c){b=void 0===b?!1:b;this.Mk();this.j&&(a?c?t4(this.j,c,b):t4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):u4(this.j))};
g.k.iB=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.yZ,this);g.av(this.player.getRootNode(),g.vZ.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Ju,c=0,d=a.length;c<d;c++)b.Sj(a[c]);this.ra.length=0;g.bW.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.O(this,a);return a.element};g.aW("annotations_module",qnb);g.aW("creatorendscreen",lmb);})(_yt_player);
